version: '3.8'

services:
  dev:
    build:
      context: .
      args:
        UBUNTU_VERSION: 22.04
        APT_MIRROR: http://jp.archive.ubuntu.com/ubuntu/
        USERNAME: vscode
        UV_VERSION: 0.8.17
        PYTHON_VERSION: 3.13.7
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - type: bind
        source: ..
        target: /workspace
        consistency: cached
      - type: bind
        source: .extensions
        target: /home/vscode/.vscode-server/extensions
        consistency: delegated
      - type: bind
        source: .bash
        target: /home/vscode/.cache/bash
        consistency: delegated
      - type: bind
        source: .venv
        target: /workspace/.venv
        consistency: delegated
      - type: bind
        source: .mypy_cache
        target: /workspace/.mypy_cache
        consistency: delegated
    extra_hosts:
      - host.docker.internal:host-gateway
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    network_mode: "bridge"
    init: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
